### PR TITLE
Pttb 4 backend use of custom request for validation

### PR DESCRIPTION
**Pull request by Pranish97**

### CODE REVIEW

**Review by Kabindrasim — APPROVED** [review]

**Review by ProshoreHR — COMMENTED** [review]
We should be using projects key for project not users.

**Review by ProshoreHR — COMMENTED** [review]
Are we removing pagination ?

**Review by ProshoreHR — COMMENTED** [review]
Why is ProjectRequest removed and used Request instead ?

**Review by ProshoreHR — CHANGES_REQUESTED** [review]
Donot import something that is not used Illuminate\Contracts\Support\Jsonable;

**Pull request merged**
